# backend/docker/docker-compose.yml

#  optional, can remove safely
# version: '3.9'  

services:
  postgres:
    image: postgres:15
    container_name: instagram_postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: instagram
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devuser" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - instagram_net

  mongo:
    image: mongo:6
    container_name: instagram_mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - instagram_net

  redis:
    image: redis:7
    container_name: instagram_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - instagram_net

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: instagram_backend
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../.env:/app/.env
      - ../.sequelizerc:/app/.sequelizerc
      - /app/node_modules
    command: >
      sh -c "
        npm run dev
      "
    restart: on-failure
    networks:
      - instagram_net

  # keycloak:
  #   image: quay.io/keycloak/keycloak:26.0.0
  #   container_name: instagram_keycloak
  #   command: start-dev --http-port=4000
  #   environment:
  #     KC_DB: postgres
  #     KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  #     KC_DB_USERNAME: devuser
  #     KC_DB_PASSWORD: devpass
  #     KC_BOOTSTRAP_ADMIN_USERNAME: admin@example.com
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - instagram_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: instagram_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - instagram_net

volumes:
  pgdata:
  mongodata:
  redisdata:

networks:
  instagram_net:
    driver: bridge
